# Generated by Django 6.0.6 on 2026-06-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Full text shown on the detail page.')),
                ('summary', models.CharField(blank=True, help_text='Short text shown in the map hover preview.', max_length=300)),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='measures/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_preview', models.BooleanField(default=False, help_text='Use this picture as the map/preview thumbnail.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='measures.measure')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='measures', to='measures.tag'),
        ),
    ]
