# Generated by Django 6.0.6 on 2026-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='description_da',
            field=models.TextField(help_text='Full text shown on the detail page.', null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='description_de',
            field=models.TextField(help_text='Full text shown on the detail page.', null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='description_en',
            field=models.TextField(help_text='Full text shown on the detail page.', null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='summary_da',
            field=models.CharField(blank=True, help_text='Short text shown in the map hover preview.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='summary_de',
            field=models.CharField(blank=True, help_text='Short text shown in the map hover preview.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='summary_en',
            field=models.CharField(blank=True, help_text='Short text shown in the map hover preview.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='title_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='caption_da',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='caption_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_da',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_de',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
