# Generated by Django 6.0.6 on 2026-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_measure_description_da_measure_description_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('kind', 'Type'), ('goal', 'Goal'), ('source', 'Source'), ('other', 'Other')], default='other', help_text="Groups the tag into a filter section; 'Type' tags colour the map markers.", max_length=10),
        ),
        migrations.AlterField(
            model_name='measure',
            name='summary',
            field=models.CharField(blank=True, help_text="The measure's goal — used as the map hover/preview text and detail-page lead.", max_length=300, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='summary_da',
            field=models.CharField(blank=True, help_text="The measure's goal — used as the map hover/preview text and detail-page lead.", max_length=300, null=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='summary_de',
            field=models.CharField(blank=True, help_text="The measure's goal — used as the map hover/preview text and detail-page lead.", max_length=300, null=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='summary_en',
            field=models.CharField(blank=True, help_text="The measure's goal — used as the map hover/preview text and detail-page lead.", max_length=300, null=True, verbose_name='goal'),
        ),
    ]
