# Generated by Django 6.0.6 on 2026-06-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0003_alter_tag_options_tag_category_alter_measure_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
    ]
